"""Constants package for SCIA integration."""

from .loads import (
    ALPHA_Q_MAIN_LANE_ONDERLIGGEND,
    ALPHA_Q_ONDERLIGGEND,
    ALPHA_Q_OTHER_LANE_ONDERLIGGEND,
    NOBS_DEFAULT,
    SIGNAGE_WEIGHT_OPTIONS,
    TANDEM_CONTACT_AREA_SIDE,
    TANDEM_LOAD_BASE_MAIN,
    TANDEM_LOAD_BASE_SECOND,
    TANDEM_LOAD_BASE_THIRD,
    UDL_OTHER_LANE_VALUE,
    UDL_REST_AREA_VALUE,
)
from .units import M_TO_MM, MM_TO_M, N_TO_KN, NM_TO_KNM

__all__ = [
    "ALPHA_Q_MAIN_LANE_ONDERLIGGEND",
    "ALPHA_Q_ONDERLIGGEND",
    "ALPHA_Q_OTHER_LANE_ONDERLIGGEND",
    "MM_TO_M",
    "M_TO_MM",
    "NM_TO_KNM",
    "NOBS_DEFAULT",
    "N_TO_KN",
    "SIGNAGE_WEIGHT_OPTIONS",
    "TANDEM_CONTACT_AREA_SIDE",
    "TANDEM_LOAD_BASE_MAIN",
    "TANDEM_LOAD_BASE_SECOND",
    "TANDEM_LOAD_BASE_THIRD",
    "UDL_OTHER_LANE_VALUE",
    "UDL_REST_AREA_VALUE",
]
