"""
Constants package for IDEA StatiCa integration.

This package contains constants specific to IDEA RCS integration,
including material properties, unit conversions, and file paths.
"""

from .formatting import (
    CHECK_VALUE_PRECISION_2,
    CHECK_VALUE_PRECISION_3,
    STRAIN_CONVERSION_FACTOR,
)
from .geometry import (
    DEFAULT_DIRECTION_VECTOR_X,
    DIRECTION_VECTOR_THRESHOLD,
    MIDPOINT_DIVISOR,
    REBAR_POSITION_HALF_OFFSET,
    SLAB_EDGE_SPACE_BOUNDARY,
    SLAB_WIDTH,
)
from .materials import (
    DEFAULT_BRIDGE_NAME,
    DEFAULT_CONCRETE_STRENGTH_CLASS,
    DEFAULT_CONCRETE_UNIT_MASS,
    DEFAULT_EPSUK,
    DEFAULT_FTK_TO_FYK_RATIO,
    DEFAULT_REBAR_POSITION_BASE,
    DEFAULT_REINFORCEMENT_CLASS,
    DEFAULT_STEEL_QUALITY,
    DEFAULT_STEEL_UNIT_MASS,
    DEFAULT_STONE_DIAMETER,
    DEFAULT_YOUNGS_MODULUS,
)
from .paths import IDEA_MATERIALS_PATH
from .units import M_TO_MM_IDEA, MM_TO_M_IDEA

__all__ = [
    "CHECK_VALUE_PRECISION_2",
    "CHECK_VALUE_PRECISION_3",
    "DEFAULT_BRIDGE_NAME",
    "DEFAULT_CONCRETE_STRENGTH_CLASS",
    "DEFAULT_CONCRETE_UNIT_MASS",
    "DEFAULT_DIRECTION_VECTOR_X",
    "DEFAULT_EPSUK",
    "DEFAULT_FTK_TO_FYK_RATIO",
    "DEFAULT_REBAR_POSITION_BASE",
    "DEFAULT_REINFORCEMENT_CLASS",
    "DEFAULT_STEEL_QUALITY",
    "DEFAULT_STEEL_UNIT_MASS",
    "DEFAULT_STONE_DIAMETER",
    "DEFAULT_YOUNGS_MODULUS",
    "DIRECTION_VECTOR_THRESHOLD",
    "IDEA_MATERIALS_PATH",
    "MIDPOINT_DIVISOR",
    "MM_TO_M_IDEA",
    "M_TO_MM_IDEA",
    "REBAR_POSITION_HALF_OFFSET",
    "SLAB_EDGE_SPACE_BOUNDARY",
    "SLAB_WIDTH",
    "STRAIN_CONVERSION_FACTOR",
]
