"""
Constants package for the src layer.

This package contains specialized constants files organized by purpose:
- parametrization: UI field options and validation constants
- technical: Technical limits, factors, and calculation constants
- plotting: Visualization styling and appearance constants
- geometry: Geometric calculations, offsets, and rendering constants
"""

# Import all constants for backward compatibility
from .geometry import (
    ANNOTATION_Y_OFFSET_CROSS_SECTION,
    ANNOTATION_Y_OFFSET_HORIZONTAL,
    AXES_CYLINDER_SECTIONS,
    AXES_LENGTH_DEFAULT,
    AXES_RADIUS_DEFAULT,
    BLACK_DOT_RADIUS,
    CYLINDER_SECTIONS_DEFAULT,
    DEFAULT_AUTO_ZONE_PAVEMENT_THICKNESS,
    DEFAULT_BERM_ZONE_PAVEMENT_THICKNESS,
    DEFAULT_LABEL_Y_OFFSET,
    DEFAULT_LANE_WIDTH,
    DIMENSION_TEXT_X_OFFSET,
    DIMENSION_TEXT_Y_OFFSET,
    MIDPOINT_DIVISOR,
    MIN_DISPLAY_WIDTH,
    MODEL_PADDING,
    PLANE_THICKNESS,
    REBAR_POSITION_HALF_OFFSET,
    SUPPORT_ANNOTATION_OFFSET,
    TEXT_X_OFFSET_CROSS_SECTION,
    TOP_VIEW_LABEL_Y_OFFSET,
    ZONE_LABEL_X_OFFSET,
)
from .parametrization import (
    CC_CLASS_OPTIONS,
    DESIGN_CODE_OPTIONS,
    LOAD_ZONE_TYPES,
    PAVEMENT_MATERIAL_OPTIONS,
    SUPPORT_TYPE_FIXED,
    SUPPORT_TYPE_FLEXIBLE,
    SUPPORT_TYPE_NONE,
    SUPPORT_TYPE_OPTIONS,
)
from .plotting import (
    DEFAULT_PLOTLY_COLORS,
    DEFAULT_ZONE_APPEARANCE_MAP,
    ZONE_BOUNDARY_ABSOLUTE_EDGE_THICKNESS,
    ZONE_BOUNDARY_SBS_LINE_THICKNESS,
    ZONE_BOUNDARY_SBS_OFFSET,
)
from .technical import (
    MAX_LOAD_ZONE_SEGMENT_FIELDS,
    MM_TO_M,
    SIGNAGE_LOAD_FACTORS,
)

__all__ = [
    "ANNOTATION_Y_OFFSET_CROSS_SECTION",
    "ANNOTATION_Y_OFFSET_HORIZONTAL",
    "AXES_CYLINDER_SECTIONS",
    "AXES_LENGTH_DEFAULT",
    "AXES_RADIUS_DEFAULT",
    "BLACK_DOT_RADIUS",
    "CC_CLASS_OPTIONS",
    "CYLINDER_SECTIONS_DEFAULT",
    "DEFAULT_AUTO_ZONE_PAVEMENT_THICKNESS",
    "DEFAULT_BERM_ZONE_PAVEMENT_THICKNESS",
    "DEFAULT_LABEL_Y_OFFSET",
    "DEFAULT_LANE_WIDTH",
    "DEFAULT_PLOTLY_COLORS",
    "DEFAULT_ZONE_APPEARANCE_MAP",
    "DESIGN_CODE_OPTIONS",
    "DIMENSION_TEXT_X_OFFSET",
    "DIMENSION_TEXT_Y_OFFSET",
    "LOAD_ZONE_TYPES",
    "MAX_LOAD_ZONE_SEGMENT_FIELDS",
    "MIDPOINT_DIVISOR",
    "MIN_DISPLAY_WIDTH",
    "MM_TO_M",
    "MODEL_PADDING",
    "PAVEMENT_MATERIAL_OPTIONS",
    "PLANE_THICKNESS",
    "REBAR_POSITION_HALF_OFFSET",
    "SIGNAGE_LOAD_FACTORS",
    "SUPPORT_ANNOTATION_OFFSET",
    "SUPPORT_TYPE_FIXED",
    "SUPPORT_TYPE_FLEXIBLE",
    "SUPPORT_TYPE_NONE",
    "SUPPORT_TYPE_OPTIONS",
    "TEXT_X_OFFSET_CROSS_SECTION",
    "TOP_VIEW_LABEL_Y_OFFSET",
    "ZONE_BOUNDARY_ABSOLUTE_EDGE_THICKNESS",
    "ZONE_BOUNDARY_SBS_LINE_THICKNESS",
    "ZONE_BOUNDARY_SBS_OFFSET",
    "ZONE_LABEL_X_OFFSET",
]
